#! /bin/bash
# /etc/init.d/pico
#
case "$1" in
  start)
    echo "Starting pico"
    /app/setup-env/pico-server &> /var/log/citytouch.log &
    ;;
  stop)
    echo "Stopping pico"
    killall pico-server
    ;;
  restart)
	$0 stop
	$0 start
	;;
  *)
    echo "Usage: /etc/init.d/pico {start|stop}"
    exit 1
    ;;
esac

exit 0