#!/usr/bin/python
import gevent
import gevent.pywsgi
import pico.server
import sys
sys.stdout = sys.stderr # sys.stdout access restricted by mod_wsgi
path = '/var/www/html/modules/' # the modules you want to be usable by Pico
if path not in sys.path:
	sys.path.insert(0, path)
pico.server.STREAMING = True
print("Serving on port 8800")
server = gevent.pywsgi.WSGIServer(('0.0.0.0', 8800), pico.server.wsgi_app)
server.serve_forever()
